# Numpy
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Import numpy

In [1]:
# import numpy
import numpy as np

### Creating Numpy Array

In [2]:
#create a 1D array
array1 = np.array([2, 3, 5, 7, 11, 13])
#print array
print(array1)
#printing type of array
print(type(array1))
#printing shape of array
print(array1.shape)
#print number of elements in array1
print(array1.size)

[ 2  3  5  7 11 13]
<class 'numpy.ndarray'>
(6,)
6


### 2-D Array

In [59]:
# creating 2 dimensional Array with shape (2,5)
array2 = np.array([[1,2,3,4,5],[6,7,8,9,101234830458123341]], dtype=np.int64)

#printing array
print(array2)

# shape of array
print(array2.shape)

# size of array -> total elements
print(array2.size)

# printing type of array
print(type(array2))

# reshape the array in 5 rows and 2 columns
print(array2.reshape(5,2))

# print dtype of array
print(array2.dtype)


[[                 1                  2                  3
                   4                  5]
 [                 6                  7                  8
                   9 101234830458123341]]
(2, 5)
10
<class 'numpy.ndarray'>
[[                 1                  2]
 [                 3                  4]
 [                 5                  6]
 [                 7                  8]
 [                 9 101234830458123341]]
int64


### 3-D Array

In [57]:
# creating 3-D array

array3 = np.array([
        [
                [1,2,3],
                [4,5,6]
        ],
        [
                [7,8,9],
                [10,11,12]
        ]
], dtype=np.int32)

# print shape of array
print(array3.shape)


# print dimensions of array
print(array3.ndim)

# print size of array
print(array3.size)

# print data type of arrayh
print(array3.dtype)


(2, 2, 3)
3
12
int32


### ndarray.ndim
the number of axes (dimensions) of the array

In [7]:
array3.ndim

3

### ndarray.shape
the dimensions of the array.
For a matrix with n rows and m columns, shape will be `(n,m)`.
The length of this tuple will be same as a the number of dimensions

In [8]:
array3.shape

(2, 2, 3)

### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

In [10]:
print(array2.size) # number of elements in array2 i.e 2*5 = 10
print(array3.size) # number of elements in array3 i.e 2*2*3 = 12


10
12


### ndarray.dtype
an object describing the type of the elements in the array.

In [61]:
print(array3.dtype) # will print int8
print(array2.dtype) # will print int64

int32
int64


### ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type `float64` has itemsize `8 (=64/8)`, while one of type complex32 has itemsize `4 (=32/8)`.

In [65]:
print(array3.itemsize) # 4 (=32/8)
print(array2.itemsize) # 8 (=64/8)

4
8


In [87]:
array5 = np.arange(10, step=0.1) 
array5.reshape(10,10)
np.zeros(45)
np.ones(12, dtype=np.int8)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)