# Numpy
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Import numpy

In [3]:
# import numpy
import numpy as np

### Creating Numpy Array

In [2]:
#create a 1D array
array1 = np.array([2, 3, 5, 7, 11, 13])
#print array
print(array1)
#printing type of array
print(type(array1))
#printing shape of array
print(array1.shape)
#print number of elements in array1
print(array1.size)

[ 2  3  5  7 11 13]
<class 'numpy.ndarray'>
(6,)
6


### 2-D Array

In [59]:
# creating 2 dimensional Array with shape (2,5)
array2 = np.array([[1,2,3,4,5],[6,7,8,9,101234830458123341]], dtype=np.int64)

#printing array
print(array2)

# shape of array
print(array2.shape)

# size of array -> total elements
print(array2.size)

# printing type of array
print(type(array2))

# reshape the array in 5 rows and 2 columns
print(array2.reshape(5,2))

# print dtype of array
print(array2.dtype)


[[                 1                  2                  3
                   4                  5]
 [                 6                  7                  8
                   9 101234830458123341]]
(2, 5)
10
<class 'numpy.ndarray'>
[[                 1                  2]
 [                 3                  4]
 [                 5                  6]
 [                 7                  8]
 [                 9 101234830458123341]]
int64


### 3-D Array

In [57]:
# creating 3-D array

array3 = np.array([
        [
                [1,2,3],
                [4,5,6]
        ],
        [
                [7,8,9],
                [10,11,12]
        ]
], dtype=np.int32)

# print shape of array
print(array3.shape)


# print dimensions of array
print(array3.ndim)

# print size of array
print(array3.size)

# print data type of arrayh
print(array3.dtype)


(2, 2, 3)
3
12
int32


### ndarray.ndim
the number of axes (dimensions) of the array



In [7]:
array3.ndim

3

### ndarray.shape
the dimensions of the array.
For a matrix with n rows and m columns, shape will be `(n,m)`.
The length of this tuple will be same as a the number of dimensions

In [8]:
array3.shape

(2, 2, 3)

### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

In [10]:
print(array2.size) # number of elements in array2 i.e 2*5 = 10
print(array3.size) # number of elements in array3 i.e 2*2*3 = 12


10
12


### ndarray.dtype
an object describing the type of the elements in the array.

In [61]:
print(array3.dtype) # will print int8
print(array2.dtype) # will print int64

int32
int64


### ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type `float64` has itemsize `8 (=64/8)`, while one of type complex32 has itemsize `4 (=32/8)`.

In [65]:
print(array3.itemsize) # 4 (=32/8)
print(array2.itemsize) # 8 (=64/8)

4
8


In [87]:
array5 = np.arange(10, step=0.1) 
array5.reshape(10,10)
np.zeros(45)
np.ones(12, dtype=np.int8)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

### Universal Functions

In [78]:
# creating an array
array = np.array([1,2,3,4,5])

# sin function
print("sin\t", np.sin(array))

# cos function
print("cos\t", np.cos(array))

# using natural log
print("log\t", np.log(array))

# variance 
print("Variance\t", np.var(array))

# standard deviation
print("SD\t",np.std(array))



# sum of array
print("Sum\t", np.sum(array))


# multiply by a number
print("multiply by a number\t",np.multiply(array, 5))

sin	 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos	 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
log	 [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Variance	 2.0
SD	 1.4142135623730951
Sum	 15
multiply by a number	 [ 5 10 15 20 25]


### Vector Operations

In [22]:
# creating two array
array1 = np.random.randint(10, 25, 5)

array2 = np.random.randint(23,45,5)

# addition of arrays
print(array1+array2)


# subtraction 
print(array1-array2)

# multiplication
print(array1*array2)

# division
print(array1/array2)

# floor division
print(array2//array1)


[39 51 59 39 52]
[ -7 -19 -11  -9 -30]
[368 560 840 360 451]
[0.69565217 0.45714286 0.68571429 0.625      0.26829268]
[1 2 1 1 3]


### Array Creation Methods

In [92]:
# np.ones((shape), dtype)
a = np.ones((3,5))
print("ones\t",a)

# np.zeros((shape), dtype)
b = np.zeros((2))
print("zeros\t",b)

# np.empty((shape), dtype) --> creates an uninitialized array
f = np.empty((2,2))
print("empty \t",f.flatten()) # flattening the array

# np.arange(start, stop, step) --> gives samples between given interval
d = np.arange(2,22)
print("arange\t",d)

# np.linspace(start, stop, number) --> returns uniform samples of size number include stop , default number is 50
e = np.linspace(0,5,10,dtype=np.float16)
print("linspace\t",e)

ones	 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
zeros	 [0. 0.]
empty 	 [0.69314718 1.09861229 1.38629436 1.60943791]
arange	 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
linspace	 [0.     0.5557 1.111  1.667  2.223  2.777  3.334  3.889  4.445  5.    ]


### Indexing

In [13]:
# Given Array
array = np.random.randint(1, 50,(4,5))
print(array)

# creating 3D array
array3d = np.random.randint(1, 50,(2,4,2))
print(array3d)

[[36 42 45 40 48]
 [ 1 10 47 10 42]
 [ 5 18 41 48 35]
 [ 4 40 43 46 43]]
[[[ 8 33]
  [35 46]
  [43 22]
  [25 24]]

 [[ 8 48]
  [30 29]
  [14 16]
  [49 43]]]


In [29]:
# accessing 1st row 3rd column
print("array[0][2]\t\t=", array[0][2])

# same can be done as follows
print("array[0,2]\t\t=", array[0,2])

# accessing 2nd element from 3rd item of 1st row (in 3D array)
print("array3d[0][2][1]\t=",array3d[0][2][1])

# accessing 2nd element from 3rd item of 1st row (in 3D array)
print("array3d[0,2,1]\t\t=",array3d[0,2,1])

array[0][2]		= 45
array[0,2]		= 45
array3d[0][2][1]	= 22
array3d[0,2,1]		= 22


### Slicing

In [27]:
array = np.random.randint(10,50, (4,5))
print("array\n", array)

array
 [[19 41 31 13 28]
 [25 43 33 15 30]
 [25 13 28 29 36]
 [15 27 27 17 33]]


In [28]:
# accessing second row from array 
print(array[1:2], end="\n\n")

# accessing all row from second row
print(array[1:], end="\n\n")

# slicing alternate rows starting from 1st row
print(array[0::2],end="\n\n")

[[25 43 33 15 30]]

[[25 43 33 15 30]
 [25 13 28 29 36]
 [15 27 27 17 33]]

[[19 41 31 13 28]
 [25 13 28 29 36]]



In [29]:
# slicing only last column from each row
print(array[:,-1:], end="\n\n")

# slicing first two columns of 1st and 2nd row
print(array[:2,:2], end="\n\n")

[[28]
 [30]
 [36]
 [33]]

[[19 41]
 [25 43]]



In [43]:
# slicing alternate elemtns from each row
print(array[:,::2], end="\n\n")

# slicing specific columns of a row
# slice 1st, 2nd and 5th element
print(array[0, [0,1,4]], end="\n\n")

# slcing specific rows 
# slice 2nd and 4th row
print(array[[1,3]])

[[19 31 28]
 [25 33 30]
 [25 28 36]
 [15 27 33]]

[19 41 28]

[[25 43 33 15 30]
 [15 27 27 17 33]]


### Filter array based on Conditions

In [54]:
array = np.arange(2,20,dtype=np.int16)
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int16)

In [48]:
# Test whether array elements are greater than 8 
# This is done element-wise
# It returns the list of Boolean element-wise
print(array > 8)

[False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True]


In [50]:
# Get the list of elements greater than 8
array[array>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int16)

In [55]:
# Get the list of even numbers
array[array%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int16)

In [70]:
# Get the list of even number greater than 8
array[(array%2==0) & (array>8)]

array([10, 12, 14, 16, 18], dtype=int16)

In [86]:
# Get the list of numbers which are either divided by 3 or greater than 5
print(array)
print(array%3)
array[array%3]

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]


array([4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3], dtype=int16)

In [78]:
# if we use any(), all() it will return single value